bhn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from baeun.views import (
    DiaryList, DiaryCreate, DiaryDetail, DiaryUpdate, DiaryDelete,
    CashbookList, CashbookCreate, CashbookDetail, CashbookUpdate, CashbookDelete,
    FriendHistoryList, FriendHistoryCreate, FriendHistoryDetail, FriendHistoryUpdate, FriendHistoryDelete,
    RelationList, RelationCreate, RelationDetail, RelationUpdate, RelationDelete, RelationMeList,
    UserCreate
)

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),

    path('diary/<int:pk>/', DiaryDetail.as_view(), name='diary_detail'),
    path('diary/update/<int:pk>/', DiaryUpdate.as_view(), name='diary_update'),
    path('diary/delete/<int:pk>/', DiaryDelete.as_view(), name='diary_delete'),
    path('diary/', DiaryList.as_view(), name='diary'),
    path('diary/form/', DiaryCreate.as_view(), name='diary_form'),

    path('cashbook/<int:pk>/', CashbookDetail.as_view(), name='cashbook_detail'),
    path('cashbook/update/<int:pk>/', CashbookUpdate.as_view(), name='cashbook_update'),
    path('cashbook/delete/<int:pk>/', CashbookDelete.as_view(), name='cashbook_delete'),
    path('cashbook/', CashbookList.as_view(), name='cashbook'),
    path('cashbook/form/', CashbookCreate.as_view(), name='cashbook_form'),

    path('relation/<int:pk>/', RelationDetail.as_view(), name='relation_detail'),
    path('relation/update/<int:pk>/', RelationUpdate.as_view(), name='relation_update'),
    path('relation/delete/<int:pk>/', RelationDelete.as_view(), name='relation_delete'),
    path('relation/', RelationList.as_view(), name='relation'),
    path('relation/me/', RelationMeList.as_view(), name='relation_me'),
    path('relation/form/', RelationCreate.as_view(), name='relation_form'),

    path('friend_history/<int:pk>/', FriendHistoryDetail.as_view(), name='friend_history_detail'),
    path('friend_history/update/<int:pk>/', FriendHistoryUpdate.as_view(), name='friend_history_update'),
    path('friend_history/delete/<int:pk>/', FriendHistoryDelete.as_view(), name='friend_history_delete'),
    path('friend_history/', FriendHistoryList.as_view(), name='friend_history'),
    path('friend_history/form/', FriendHistoryCreate.as_view(), name='friend_history_form'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreate.as_view(), name='register'),
    path('accounts/register/done/', TemplateView.as_view(template_name='registration/register_done.html'),
         name='register_done'),
    path('admin/', admin.site.urls),
]

baeun/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Cashbook(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    event_dt = models.DateField()
    money_amount = models.IntegerField()
    money_usage = models.CharField(max_length=40)
    money_usage_group = models.CharField(max_length=10)
    counting_type = models.CharField(max_length=8)
    reg_dt = models.DateField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('cashbook')

    class Meta:
        verbose_name_plural = "회계장부"
        ordering = ['-event_dt', 'money_usage_group']


class Diary(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    event_dt = models.DateField()
    reg_dt = models.DateField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('diary')

    class Meta:
        verbose_name_plural = "다이어리"
        ordering = ['-event_dt', '-id']


class Activity(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    event_dt = models.DateField()
    content = models.CharField(max_length=100)
    activity_group = models.CharField(max_length=10)
    reg_dt = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "활동들"


class Todo(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    condition = models.CharField(max_length=70)
    content = models.TextField()
    check_yn = models.BooleanField()
    reg_dt = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "할일"


class Habit(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    condition = models.CharField(max_length=70)
    content = models.TextField()
    reg_dt = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "습관"


# 2019-02-22 added
class Relation(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    friend_id = models.CharField(max_length=150)
    total_trust_point = models.IntegerField()
    first_friend_dt = models.DateField()
    reg_dt = models.DateField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('relation')

    def __str__(self):
        return '%s-%s' % (self.owner, self.friend_id)

    class Meta:
        verbose_name_plural = "사람들"
        ordering = ['-first_friend_dt', '-id']


# 2019-02-22 added
class FriendHistory(models.Model):
    relation = models.ForeignKey(Relation, on_delete=models.CASCADE)
    trust_point = models.IntegerField()
    content = models.TextField()
    reg_dt = models.DateField(auto_now_add=True)
    event_dt = models.DateField(null=True)

    def save(self, *args, **kwargs):
        pre_r = FriendHistory.objects.filter(id=self.id).first()
        r = Relation.objects.get(id=self.relation.id)
        if pre_r is None:
            new_trust_point = self.trust_point
        else:
            new_trust_point = self.trust_point - pre_r.trust_point
        r.total_trust_point += new_trust_point
        r.save()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        r = Relation.objects.get(id=self.relation.id)
        r.total_trust_point -= self.trust_point
        r.save()
        super().delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('friend_history')

    def __str__(self):
        return self.content

    class Meta:
        verbose_name_plural = "지인기록"
        ordering = ['-event_dt']


class MoodLog(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    mood = models.IntegerField()
    event_dttm = models.DateTimeField()
    reason = models.TextField()
    reg_dt = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "기분기록"


class Chronicle(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    primary_tag = models.CharField(max_length=20, null=True, blank=True)
    year = models.IntegerField()
    residence = models.CharField(max_length=90)
    content = models.TextField()
    new_people = models.TextField(null=True, blank=True)
    reg_dt = models.DateField(auto_now_add=True)
    upd_dt = models.DateField(auto_now=True)

    class Meta:
        verbose_name_plural = "연대기"

baeun/views.py
from baeun.models import Diary, Cashbook, Relation, FriendHistory
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm


class UserCreate(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')


class DiaryList(LoginRequiredMixin, ListView):
    model = Diary
    context_object_name = 'diary_list'
    paginate_by = 15

    def get_queryset(self):
        queryset = super(DiaryList, self).get_queryset()
        queryset = queryset.filter(owner=self.request.user)
        return queryset


class DiaryCreate(CreateView):
    model = Diary
    fields = ['owner', 'content', 'event_dt']

    def get_initial(self):
        initial = super(DiaryCreate, self).get_initial()
        initial.update({'owner': self.request.user})
        return initial

    # def __init__(self, *args, **kwargs):
    #     super(DiaryCreate, self).__init__(*args, **kwargs)
    #     self.fields['owner'].disabled = True


class DiaryDetail(DetailView):
    model = Diary


class DiaryUpdate(UpdateView):
    model = Diary
    fields = ['content', 'event_dt']


class DiaryDelete(DeleteView):
    model = Diary
    success_url = reverse_lazy('diary')


# Cashbook
class CashbookList(LoginRequiredMixin, ListView):
    model = Cashbook
    context_object_name = 'cashbook_list'
    paginate_by = 20

    def get_queryset(self):
        queryset = super(CashbookList, self).get_queryset()
        queryset = queryset.filter(owner=self.request.user)
        return queryset


class CashbookCreate(CreateView):
    model = Cashbook
    fields = ['owner', 'event_dt', 'money_usage', 'money_amount', 'money_usage_group', 'counting_type']

    def get_initial(self):
        initial = super(CashbookCreate, self).get_initial()
        initial.update({'owner': self.request.user})
        return initial


class CashbookDetail(DetailView):
    model = Cashbook


class CashbookUpdate(UpdateView):
    model = Cashbook
    fields = ['event_dt', 'money_usage', 'money_amount', 'money_usage_group', 'counting_type']


class CashbookDelete(DeleteView):
    model = Cashbook
    success_url = reverse_lazy('cashbook')


# Relation
class RelationList(LoginRequiredMixin, ListView):
    model = Relation
    context_object_name = 'relation_list'
    paginate_by = 20

    def get_queryset(self):
        queryset = super(RelationList, self).get_queryset()
        queryset = queryset.filter(owner=self.request.user)
        return queryset


class RelationCreate(CreateView):
    model = Relation
    fields = ['owner', 'friend_id', 'total_trust_point', 'first_friend_dt']

    def get_initial(self):
        initial = super(RelationCreate, self).get_initial()
        initial.update({'owner': self.request.user})
        return initial


class RelationDetail(DetailView):
    model = Relation


class RelationUpdate(UpdateView):
    model = Relation
    fields = ['friend_id', 'total_trust_point', 'first_friend_dt']


class RelationDelete(DeleteView):
    model = Relation
    success_url = reverse_lazy('relation')


class RelationMeList(LoginRequiredMixin, ListView):
    template_name = 'baeun/relation_me_list.html'
    model = Relation
    context_object_name = 'relation_me_list'
    paginate_by = 20

    def get_queryset(self):
        queryset = super(RelationMeList, self).get_queryset()
        queryset = queryset.filter(friend_id=self.request.user)
        return queryset


# friendHistory
# Relation
class FriendHistoryList(LoginRequiredMixin, ListView):
    model = FriendHistory
    context_object_name = 'friend_history_list'
    paginate_by = 20

    # def get_queryset(self):
    #     queryset = super(FriendHistoryList, self).get_queryset()
    #     queryset = queryset.filter(owner=self.request.user)
    #     return queryset


class FriendHistoryCreate(CreateView):
    model = FriendHistory
    fields = ['relation', 'trust_point', 'content']

    # def get_initial(self):
    #     initial = super(FriendHistoryCreate, self).get_initial()
    #     initial.update({'owner': self.request.user})
    #     return initial


class FriendHistoryDetail(DetailView):
    model = FriendHistory


class FriendHistoryUpdate(UpdateView):
    model = FriendHistory
    fields = ['trust_point', 'content']


class FriendHistoryDelete(DeleteView):
    model = FriendHistory
    success_url = reverse_lazy('friend_history')

templates/baeun/cashbook_confirm_delete.html
{% extends "base.html" %}
{% block title %}
가계부
{% endblock %}
{% block content %}
    <a href="{% url "cashbook" %}" class="btn">목록으로</a>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="삭제하기">
</form>
{% endblock %}

templates/baeun/cashbook_form.html
{% extends "base.html" %}
{% block title %}
    가계부
{% endblock %}
{% block style %}
    <style>
    input{
        width: 6rem;
        padding:4px 6px;
    }
    </style>
{% endblock %}

{% block content %}
    <p>
        <a href="{% url "cashbook" %}" class="btn">목록으로</a>
    </p>
    <h1>가계부</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="저장">
</form>
{% endblock %}
{% block script %}
        <script>
        $(function () {
            $("#id_event_dt").datepicker({
                dateFormat: "yy-mm-dd",
                dayNamesMin: ["일", "월", "화", "수", "목", "금", "토"],
                monthNames: [ "1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월" ]
            });
            //$('#id_owner').attr("disabled", true);
        });
    </script>
{% endblock %}

templates/baeun/cashbook_list.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}
    가계부
{% endblock %}
{% block style %}
    <style>
    td:nth-child(4){
        text-align: right;
    }
    </style>
{% endblock %}
{% block content %}
    <h1>가계부</h1>
    <div class="mb1">
        <a href="{% url 'cashbook_form' %}" class="btn">등록</a>
    </div>
    <table>
        {% for article in cashbook_list %}
            <tr>
                <td><a href="{% url "cashbook_detail" article.id %}">{{ article.id }}</a></td>
                <td>{{ article.event_dt }}</td>
                <td>{{ article.money_usage }}</td>
                <td>{{ article.money_amount|intcomma }}</td>
                <td>{{ article.money_usage_group }}</td>
                <td>{{ article.counting_type }}</td>
                <td>
                    <a href="{% url "cashbook_update" article.id %}"><i class="material-icons">edit</i></a>
                    <a href="{% url "cashbook_delete" article.id %}"><i class="material-icons">delete</i></a>
                </td>
            </tr>
        {% endfor %}
    </table>
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

templates/baeun/diary_confirm_delete.html
{% extends "base.html" %}
{% block title %}
Diary
{% endblock %}
{% block content %}
    <a href="{% url "diary" %}" class="btn">목록으로</a>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="삭제하기">
</form>
{% endblock %}

templates/baeun/diary_detail.html
{% extends "base.html" %}
{% block title %}
Diary
{% endblock %}
{% block content %}
    <p>
    <a href="{% url "diary" %}" class="btn">목록으로</a>
    </p>
<h1>다이어리</h1>
<p>소유자 : {{ object.owner }}</p>
<p>글아이디 : {{ object.id }}</p>
<p>내용 : {{ object.content }}</p>
<p>내용일자 : {{ object.event_dt }}</p>
{% endblock %}

templates/baeun/diary_form.html
{% extends "base.html" %}
{% block title %}
    Diary Form
{% endblock %}
{% block style %}
    <style>
    input{
        width: 6rem;
        padding:4px 6px;
    }
    </style>
{% endblock %}

{% block content %}
    <p>
        <a href="{% url "diary" %}" class="btn">목록으로</a>
    </p>
    <h1>다이어리</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="저장">
</form>
{% endblock %}
{% block script %}
        <script>
        $(function () {
            $("#id_event_dt").datepicker({
                dateFormat: "yy-mm-dd",
                dayNamesMin: ["일", "월", "화", "수", "목", "금", "토"],
                monthNames: [ "1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월" ]
            });
            //$('#id_owner').attr("disabled", true);
            //CKEDITOR.replace( 'id_content' );
        });
    </script>
{% endblock %}

templates/baeun/diary_list.html
{% extends "base.html" %}
{% block title %}
    Diary
{% endblock %}
{% block style %}
    <style>
        td:nth-child(1), td:nth-child(3), td:nth-child(4), td:nth-child(5) {
            white-space: nowrap;
        }

        td:nth-child(2) {
            word-break: break-all;
        }
    </style>
{% endblock %}
{% block content %}
    <h1>다이어리</h1>
    <div class="mb1">
        <a href="{% url 'diary_form' %}" class="btn">등록</a>
    </div>
        {% for article in diary_list %}
            <div class="card">
            <div class="row jc-betw">
            <div>내용일자 : {{ article.event_dt }}</div>
            <div class="text-right">
                <a href="{% url "diary_update" article.id %}"><i class="material-icons">edit</i></a>
                <a href="{% url "diary_delete" article.id %}"><i class="material-icons">delete</i></a>
            </div>
            </div>
            <p>{{ article.content }}</p>
            </div>
        {% endfor %}
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

templates/baeun/friendhistory_detail.html
{% extends "base.html" %}
{% block title %}
지인기록
{% endblock %}
{% block content %}
    <p><a href="{% url "friend_history" %}" class="btn">목록으로</a></p>
<h1>지인기록</h1>
<p>관계아이디 : {{ object.relation }}</p>
<p>신뢰포인트 : {{ object.trust_point }}</p>
<p>내용 : {{ object.content }}</p>
<p>등록일자 : {{ object.reg_dt }}</p>
{% endblock %}

templates/baeun/friendhistory_form.html
{% extends "base.html" %}
{% block title %}
    지인기록
{% endblock %}
{% block style %}
    <style>
    input{
        width: 6rem;
        padding:4px 6px;
    }
    </style>
{% endblock %}

{% block content %}
    <p>
        <a href="{% url "friend_history" %}" class="btn">목록으로</a>
    </p>
    <h1>지인기록</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="저장">
</form>
{% endblock %}
{% block script %}
        <script>
        $(function () {
            $("#id_event_dt").datepicker({
                dateFormat: "yy-mm-dd",
                dayNamesMin: ["일", "월", "화", "수", "목", "금", "토"],
                monthNames: [ "1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월" ]
            });
            //$('#id_owner').attr("disabled", true);
        });
    </script>
{% endblock %}

templates/baeun/friendhistory_list.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}
    지인기록
{% endblock %}
{% block content %}
    <h1>지인기록</h1>
    <div class="mb1">
        <a href="{% url 'friend_history_form' %}" class="btn">등록</a>
    </div>
    <table>
        {% for article in friend_history_list %}
            <tr>
                <td><a href="{% url "friend_history_detail" article.id %}">{{ article.id }}</a></td>
                <td>{{ article.relation }}</td>
                <td>{{ article.trust_point }}</td>
                <td>{{ article.content }}</td>
                <td>{{ article.reg_dt }}</td>
                <td>
                    <a href="{% url "friend_history_update" article.id %}"><i class="material-icons">edit</i></a>
                    <a href="{% url "friend_history_delete" article.id %}"><i class="material-icons">delete</i></a>
                </td>
            </tr>
        {% endfor %}
    </table>
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

templates/baeun/relation_confirm_delete.html
{% extends "base.html" %}
{% block title %}
사람들
{% endblock %}
{% block content %}
    <a href="{% url "relation" %}" class="btn">목록으로</a>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="삭제하기">
</form>
{% endblock %}

templates/baeun/relation_detail.html
{% extends "base.html" %}
{% block title %}
사람들
{% endblock %}
{% block content %}
    <p><a href="{% url "relation" %}" class="btn">목록으로</a></p>
<h1>사람들</h1>
<p>소유자 : {{ object.owner }}</p>
<p>친구아이디 : {{ object.friend_id }}</p>
<p>신뢰포인트 : {{ object.total_trust_point }}</p>
<p>최초일자 : {{ object.first_friend_dt }}</p>
<p>등록일자 : {{ object.reg_dt }}</p>
{% endblock %}

templates/baeun/relation_form.html
{% extends "base.html" %}
{% block title %}
    사람들
{% endblock %}
{% block style %}
    <style>
    input{
        width: 6rem;
        padding:4px 6px;
    }
    </style>
{% endblock %}

{% block content %}
    <p>
        <a href="{% url "relation" %}" class="btn">목록으로</a>
    </p>
    <h1>사람들</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="저장">
</form>
{% endblock %}
{% block script %}
        <script>
        $(function () {
            $("#id_first_friend_dt").datepicker({
                dateFormat: "yy-mm-dd",
                dayNamesMin: ["일", "월", "화", "수", "목", "금", "토"],
                monthNames: [ "1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월" ]
            });
            //$('#id_owner').attr("disabled", true);
        });
    </script>
{% endblock %}

templates/baeun/relation_me_list.html
{% extends "base.html" %}
{% block title %}
    사람들
{% endblock %}
{% block content %}
    <h1>나를 등록한 사람들</h1>
    <div class="mb1">
        <a href="{% url 'relation' %}" class="btn">내가 등록한 사람들 보기</a>
    </div>
    <table>
    <thead>
    <tr>
        <th>ID</th>
        <th>소유자</th>
        <th>친구아이디</th>
        <th>총신뢰포인트</th>
        <th>최초일자</th>
        <th>등록일자</th>
    </tr>
    </thead>
    <tbody>
        {% for article in relation_me_list %}
            <tr>
                <td><a href="{% url "relation_detail" article.id %}">{{ article.id }}</a></td>
                <td>{{ article.owner }}</td>
                <td>{{ article.friend_id }}</td>
                <td>{{ article.total_trust_point }}</td>
                <td>{{ article.first_friend_dt }}</td>
                <td>{{ article.reg_dt }}</td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}